In [276]:
# Tratando dados ausentes

In [277]:
import pandas as pd
import numpy as np

In [278]:
string_data = pd.Series(['aadvark','artichoke','np.nan','avocado'])

In [279]:
string_data

0      aadvark
1    artichoke
2       np.nan
3      avocado
dtype: object

In [280]:
string_data.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [281]:
string_data[0] = None


In [282]:
string_data.isnull()


0     True
1    False
2    False
3    False
dtype: bool

In [283]:
# Filtrando dados ausentes

In [284]:
from numpy import nan as NA

In [285]:
data = pd.Series([1,NA, 3.5, NA, 7])

In [286]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [287]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [288]:
data=pd.DataFrame([[1, 6.5, 3], [1, NA, NA], [NA,NA, NA], [NA, 6.5, 3]])

In [289]:
cleaned = data.dropna()

In [290]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [291]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [292]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [293]:
data[4] = NA

In [294]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [295]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [296]:
df = pd.DataFrame(np.random.randn(7,3))

In [297]:
df.iloc[:4,1] = NA

In [298]:
df.iloc[:2, 2] = NA

In [299]:
df

0         1         2
0 -0.585365       NaN       NaN
1  0.299109       NaN       NaN
2 -0.571632       NaN  0.455452
3  0.865982       NaN  0.447816
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [300]:
df.dropna()

0         1         2
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [301]:
df.dropna()

0         1         2
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [302]:
df.dropna(thresh=2)

0         1         2
2 -0.571632       NaN  0.455452
3  0.865982       NaN  0.447816
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [303]:
#Preenchendo dados ausentes'

In [304]:
df.fillna(0)

0         1         2
0 -0.585365  0.000000  0.000000
1  0.299109  0.000000  0.000000
2 -0.571632  0.000000  0.455452
3  0.865982  0.000000  0.447816
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [305]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.585365  0.500000  0.000000
1  0.299109  0.500000  0.000000
2 -0.571632  0.500000  0.455452
3  0.865982  0.500000  0.447816
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [306]:
_=df.fillna(0, inplace=True)

In [307]:
df

0         1         2
0 -0.585365  0.000000  0.000000
1  0.299109  0.000000  0.000000
2 -0.571632  0.000000  0.455452
3  0.865982  0.000000  0.447816
4  1.501637  1.700405  1.299782
5 -2.240400 -0.140630 -0.099509
6 -0.687661  0.730769  0.063535

In [308]:
df = pd.DataFrame(np.random.randn(6, 3))

In [309]:
df.iloc[2:,1] = NA


In [310]:
df.iloc[4:, 2] = NA

In [311]:
df

0         1         2
0 -0.753969 -1.260762 -0.060559
1 -0.623496  0.630165 -0.376479
2 -0.703126       NaN  0.753502
3  0.618194       NaN -0.791985
4 -0.617900       NaN       NaN
5  1.808475       NaN       NaN

In [312]:
df.fillna(method='ffill')

0         1         2
0 -0.753969 -1.260762 -0.060559
1 -0.623496  0.630165 -0.376479
2 -0.703126  0.630165  0.753502
3  0.618194  0.630165 -0.791985
4 -0.617900  0.630165 -0.791985
5  1.808475  0.630165 -0.791985

In [313]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.753969 -1.260762 -0.060559
1 -0.623496  0.630165 -0.376479
2 -0.703126  0.630165  0.753502
3  0.618194  0.630165 -0.791985
4 -0.617900       NaN -0.791985
5  1.808475       NaN -0.791985

In [314]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [315]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [316]:
#Transformação de dados

In [317]:
#Removendo duplicatas

In [318]:
data = pd.DataFrame({'k1': ['one', 'two']*3+['two'], 'k2':[1, 1, 2, 3, 3, 4, 4]})

In [319]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [320]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [321]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [322]:
data['v1'] = range(7)

In [323]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [324]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [325]:
data.drop_duplicates(['k1','k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [326]:
# Transformando dados usando uma função ou um mapeamento

In [327]:
data = pd.DataFrame({'food':['bacon','pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [328]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [329]:
meat_to_animal = {'bacon':'pig', 
                  'pulled pork':'pig',
                  'pastrami': 'cow',
                  'corned beef':'cow',
                  'honey ham':'pig',
                  'nova lox':'salmon'
                  }

In [330]:
lowercased = data['food'].str.lower()

In [331]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [332]:
data['animal'] = lowercased.map(meat_to_animal)

In [333]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [334]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [335]:
# Substituindo valores

In [336]:
data = pd.Series([1., -999, 2, -999, -1000, 3])

In [337]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [338]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [339]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [340]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [341]:
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [342]:
# Renomenado os índices dos eixos

In [343]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index=['Ohio','Colorado','New York'],
                    columns=['one','two','three','four'])

In [344]:
transform = lambda x: x[:4].upper()

In [345]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [346]:
data.index = data.index.map(transform)

In [347]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [348]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [349]:
data.rename(index={'OHIO':'INDIANA'},
            columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [350]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [351]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [352]:
# Discretização e compartimentalização (binning)

In [353]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [354]:
bins = [18, 25, 35, 60, 100]

In [355]:
cats = pd.cut(ages, bins)

In [356]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [357]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [358]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [359]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [360]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [361]:
group_names = ['Youth','YoungAdult', 'MiddleAged','Senior']

In [362]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [363]:
data = np.random.rand(20)

In [364]:
pd.cut(data, 4, precision=2)

[(0.66, 0.87], (0.004, 0.22], (0.44, 0.66], (0.66, 0.87], (0.66, 0.87], ..., (0.004, 0.22], (0.22, 0.44], (0.22, 0.44], (0.44, 0.66], (0.44, 0.66]]
Length: 20
Categories (4, interval[float64, right]): [(0.004, 0.22] < (0.22, 0.44] < (0.44, 0.66] < (0.66, 0.87]]

In [365]:
data = np.random.randn(1000) # Normalmente distribuídos

In [366]:
cats = pd.qcut(data, 4) # Separa em quantis

In [367]:
cats

[(-0.701, -0.0267], (0.647, 2.998], (0.647, 2.998], (-0.701, -0.0267], (0.647, 2.998], ..., (-2.983, -0.701], (-2.983, -0.701], (-2.983, -0.701], (-2.983, -0.701], (-0.0267, 0.647]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.983, -0.701] < (-0.701, -0.0267] < (-0.0267, 0.647] < (0.647, 2.998]]

In [368]:
pd.value_counts(cats)

(-2.983, -0.701]     250
(-0.701, -0.0267]    250
(-0.0267, 0.647]     250
(0.647, 2.998]       250
Name: count, dtype: int64

In [369]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

[(-1.289, -0.0267], (1.286, 2.998], (1.286, 2.998], (-1.289, -0.0267], (-0.0267, 1.286], ..., (-1.289, -0.0267], (-1.289, -0.0267], (-1.289, -0.0267], (-2.983, -1.289], (-0.0267, 1.286]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.983, -1.289] < (-1.289, -0.0267] < (-0.0267, 1.286] < (1.286, 2.998]]

In [370]:
# Detectando e filtrando valores discrepantes

In [371]:
data = pd.DataFrame(np.random.randn(1000,4))

In [372]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.037021    -0.003965    -0.052188    -0.016652
std       1.005000     0.987992     0.985379     0.994661
min      -3.030037    -2.694776    -2.947019    -3.624115
25%      -0.701646    -0.668818    -0.765095    -0.676348
50%       0.008851    -0.011128    -0.020113     0.014565
75%       0.658967     0.603051     0.648477     0.665280
max       3.445112     3.457926     2.763975     2.839773

In [373]:
col = data[2]

In [374]:
col[np.abs(col)>3]

Series([], Name: 2, dtype: float64)

In [375]:
filtered_data = data.loc[(np.abs(data) > 3).any(axis=1)]



In [376]:
filtered_data

0         1         2         3
54  -0.461899  3.061902  0.829755 -1.221546
165  3.445112  1.342895  0.248402  0.277118
475 -1.233590 -0.645974 -0.147492 -3.142335
743 -0.552620  3.008783  0.071851 -0.012718
795  0.140616  3.036726  0.490888 -0.326867
849 -0.240643  3.379513  1.834014  0.912421
867  0.009692 -0.647674 -0.978475 -3.624115
932 -3.030037 -0.045650  0.268441 -0.133474
978  0.241299 -0.893946 -0.204548 -3.077029
998  0.504490  3.457926 -1.422834  0.251251

In [377]:
data[np.abs(data)>3] = np.sign(data)*3

In [378]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.037436    -0.004910    -0.052188    -0.015809
std       1.003464     0.984929     0.985379     0.991915
min      -3.000000    -2.694776    -2.947019    -3.000000
25%      -0.701646    -0.668818    -0.765095    -0.676348
50%       0.008851    -0.011128    -0.020113     0.014565
75%       0.658967     0.603051     0.648477     0.665280
max       3.000000     3.000000     2.763975     2.839773

In [379]:
np.sign(data)

0    1    2    3
0   -1.0  1.0  1.0 -1.0
1    1.0 -1.0 -1.0  1.0
2    1.0  1.0 -1.0  1.0
3    1.0  1.0  1.0  1.0
4    1.0  1.0 -1.0 -1.0
..   ...  ...  ...  ...
995  1.0 -1.0 -1.0  1.0
996 -1.0 -1.0 -1.0  1.0
997 -1.0  1.0  1.0 -1.0
998  1.0  1.0 -1.0  1.0
999 -1.0 -1.0 -1.0  1.0

[1000 rows x 4 columns]

In [380]:
# Permutação e amostragem aleatória

In [381]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [382]:
sampler = np.random.permutation(5)

In [383]:
sampler

array([1, 3, 0, 2, 4])

In [384]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [385]:
df.sample(3)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [386]:
choices = pd.Series([5,7,-1,6,4])

In [387]:
draws = choices.sample(n=10, replace=True)

In [388]:
draws

2   -1
2   -1
4    4
3    6
0    5
3    6
3    6
4    4
2   -1
4    4
dtype: int64

In [389]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                   'data1':range(6)})

In [390]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [391]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [392]:

dummies = pd.get_dummies(df['key'], prefix='key')

In [393]:
df_with_dumy = df[['data1']].join(dummies)

In [394]:
df_with_dumy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [395]:
mnames = ['movie_id', 'title','genres']

In [396]:
movies = pd.read_table("C:\\Users\\alana\\OneDrive\\Documentos\\GitHub\\Python_Para_Análise_de_Dados\\pydata-book\\datasets\\movielens\\movies.dat", sep='::', header=None, names=mnames)

C:\Users\alana\AppData\Local\Temp\ipykernel_7028\3827974368.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table("C:\\Users\\alana\\OneDrive\\Documentos\\GitHub\\Python_Para_Análise_de_Dados\\pydata-book\\datasets\\movielens\\movies.dat", sep='::', header=None, names=mnames)


In [397]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [398]:
all_genres =[]

In [399]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [400]:
genres = pd.unique(all_genres)

In [401]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [402]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [403]:
print(zero_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [404]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [405]:
gen = movies.genres[0]

In [406]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [407]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [408]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [409]:
movies_windic = movies.join(dummies.add_prefix('Genre'))

In [410]:
movies_windic.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
GenreAnimation                              1.0
GenreChildren's                             1.0
GenreComedy                                 1.0
GenreAdventure                              0.0
GenreFantasy                                0.0
GenreRomance                                0.0
GenreDrama                                  0.0
GenreAction                                 0.0
GenreCrime                                  0.0
GenreThriller                               0.0
GenreHorror                                 0.0
GenreSci-Fi                                 0.0
GenreDocumentary                            0.0
GenreWar                                    0.0
GenreMusical                                0.0
GenreMystery                                0.0
GenreFilm-Noir                              0.0
GenreWestern                            

In [411]:
np.random.seed(12345)

In [412]:
values = np.random.rand(10)

In [413]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [414]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [415]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [ ]:
#Manipulação de strings

In [ ]:
# Métodos de objetos string

In [416]:
val = ' a, b, guido'

In [417]:
val.split(',')

[' a', ' b', ' guido']

In [418]:
pieces = [x.strip() for x in val.split(',')]

In [419]:
pieces

['a', 'b', 'guido']

In [420]:
first, second, third = pieces

In [421]:
first + '::' + second + '::' + third

'a::b::guido'

In [422]:
'::'.join(pieces)

'a::b::guido'

In [423]:
'guido' in val

True

In [424]:
val.index(',')

2

In [425]:
val.find(':')

-1

In [426]:
# Erro proposital
val.index(':')

ValueError: substring not found

In [427]:
val.count(',')

2

In [428]:
val.replace(',','::')

' a:: b:: guido'

In [429]:
val.replace(',','')

' a b guido'

In [ ]:
#Expressões regulares

In [430]:

import re

In [431]:
text = 'Foo   bar\t baz \tqux'

In [432]:
re.split('\s+', text)

['Foo', 'bar', 'baz', 'qux']

In [433]:
regex = re.compile('\s+')

In [434]:
regex.split(text)

['Foo', 'bar', 'baz', 'qux']

In [435]:
regex.findall(text)

['   ', '\t ', ' \t']

In [436]:
text = """Dave dave@google.com
Steve seteve@gmail.com
Rob rob@gmail.com
Ryan ryan@gmail.com
"""

In [439]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [441]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [442]:
regex.findall(text)

['dave@google.com', 'seteve@gmail.com', 'rob@gmail.com', 'ryan@gmail.com']

In [443]:
m = regex.search(text)

In [444]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [445]:
print(regex.match(text))

None


In [447]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [454]:
pattern = r'([A-Z0-9._%+-]+)+@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [455]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [456]:
m = regex.match('wes@bright.net')

In [457]:
m.groups()

('wes', 'bright', 'net')

In [458]:
print(regex.sub(r'Username: \1, Domain: \2. Suffix: \3', text))

Dave Username: dave, Domain: google. Suffix: com
Steve Username: seteve, Domain: gmail. Suffix: com
Rob Username: rob, Domain: gmail. Suffix: com
Ryan Username: ryan, Domain: gmail. Suffix: com



In [ ]:
# Funções de string vetorizadas no pandas


In [459]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes':np.nan}

In [460]:
data = pd.Series(data)

In [461]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [462]:
data.isnull

<bound method Series.isnull of Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object>

In [463]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [464]:
pattern

'([A-Z0-9._%+-]+)+@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [465]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [466]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [470]:
print(type(matches))
print(matches)


<class 'pandas.core.series.Series'>
Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object


In [472]:
matches.astype(str).str[0]


Dave     T
Steve    T
Rob      T
Wes      n
dtype: object

In [473]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object